filme/urls.py
from django.urls import path,include
from .views import Homepage, Homefilmes, Detalhefilme, teste

app_name="filme"
urlpatterns = [
    path('teste/', teste, name='teste'),
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', Detalhefilme.as_view(), name="detalhesfilme")
]

primeflix_django/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace="filme")), 
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from distutils.command.upload import upload
from pyexpat import model
from django.db import models
from django.utils import timezone
# Create your models here.

TIPOS_CATEGORAIA = (
    ('TERROR', 'Terror'),
    ('SUSPENSE','Supense'),
    ('ANIMACAO', 'Animação'),
    ('ACAO', 'Ação'),
    ('OUTROS', 'Outros'),
)

TEMPORADAS = (
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
    (6,6),
    (7,7),
    (8,8),
    (9,9),
)

TIPOS = (
    ("FILME","Filme"),
    ("SERIE","Série"),
)

class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(max_length=4000)
    categoria = models.CharField(max_length=20, choices=TIPOS_CATEGORAIA)
    vizualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)
    thumb = models.ImageField(upload_to='thumb_filmes')
    tipo = models.CharField(max_length=30, choices=TIPOS,default="#")

    def __str__(self):
        return self.titulo

    @property
    def get_temp(self):
        t = 0
        lista = []
        for ep in self.episodios.all():
            lista.append(ep.temporada)
        for i in lista:
            if i > t:
                t = i
        t = range(t)
        return t    

class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()
    ep_num = models.IntegerField(default=0)
    temporada = models.IntegerField(default=0, choices=TEMPORADAS)

    def __str__(self):
        return self.titulo
    
    

filme/views.py
from multiprocessing import context
from django.shortcuts import render
from .models import *
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from django.http import Http404
# Create your views here.

def teste(request):
    return render(request, 'filme/teste.html')

class Homepage(TemplateView):
    template_name = "filme/homepage.html"
    

'''def homepage(request):
    return render(request, 'filme/homepage.html')'''

'''def homefilmes(request):
    context = {}
    lista_filmes = Filme.objects.all()
    context['lista_filmes'] =  lista_filmes
    return render(request, 'filme/homefilmes.html', context)'''
class Homefilmes(ListView):
    template_name = "filme/homefilmes.html"
    model = Filme


class Detalhefilme(DetailView):
    template_name = "filme/detalhefilme.html"
    model = Filme


    def get(self, request, *args, **kwargs):
        filme_ = self.get_object()
        filme_.vizualizacoes += 1
        filme_.save()
        return super().get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super(Detalhefilme, self).get_context_data(**kwargs)
        filmes_rel = Filme.objects.filter(categoria=self.get_object().categoria)
        filmes_rel = filmes_rel.exclude(titulo=self.get_object().titulo)
        filmes_rel = filmes_rel.order_by('titulo')[:6]
        context['filmes_rel'] = filmes_rel
        horse = Filme.objects.get(pk = self.kwargs['pk'])
        if not horse:
            raise Http404
        return context

filme/templates/filme/detalhefilme.html
{% extends 'base.html' %}


{% block title %}
    Primeflix - {{object.titulo}}
{% endblock %}


{% block content %}
    <main class="bg-primary_black min-h-screen w-full">
        <section class="h-screen relative bg-no-repeat bg-black bg-blend-overlay bg-opacity-50 border-red-600 border-b-4 pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{object.thumb.url}}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{object.titulo}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{object.descricao|slice:":110"}}...
                </p>
                <div class="flex my-4">
                    <a href="{{object.episodios.first.video}}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section> 
        <section class='bg-primary_black flex justify-center pt-10'>
            <div class="p-8 w-10/12 relative">
                <h2 class="text-gray-200 text-2xl font-medium">
                    Description
                </h2>
                <div class="flex justify-left  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-base">
                        {{object.descricao}}
                    </p>
                </div>
                <div style='margin-top:2rem;margin-bottom:2rem;'>
                    {% if object.tipo == 'FILME' %}
                    <h2 class="text-gray-200 text-2xl font-medium">
                        Movie
                    </h2>
                        <h3 class='text-base'>
                            <a href="{{object.episodios.first.video}}">
                            {{object.episodios.first.titulo}}
                            </a>
                        </h3>
                    {% endif %}   
                    {% if object.tipo == 'SERIE' %}
                    <h2 class="text-gray-200 text-2xl font-medium">
                        Episodes
                    </h2>
                        <h3 class='text-base'>
                            {% for temp in object.get_temp %}
                    <div class="py-2 space-y-4">
                        <div>
                            <h2 class="text-red-700 underline">Season {{forloop.counter}}:</h2>
                                {% for ep in object.episodios.filter %}
                                    {% if ep.temporada == forloop.parentloop.counter %}
                                        <a href="{{ep.video}}"><p>{{ep}}</p></a>
                                    {% endif %}
                                {% endfor %}
                        </div>
                    </div>
                            {% endfor %}
                        </h3>
                    {% endif %}    
                </div>
            </div>
        </section>    

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Relacionados
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for item in filmes_rel %}
                        {% if forloop.counter < 4 %}
                        <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-80 border-2 ">
                            <a href="{% url 'filme:detalhesfilme' item.pk %}">
                                <img src="{{item.thumb.url}}" class="object-cover w-full h-full " alt="">
                            </a>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </section>

    </main>
{% endblock %}

filme/templates/filme/homefilmes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Primeflix - Filmes
{% endblock %}


{% block head %}
    <style>
        $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;
    
    .item {
      padding: 0 2px;
      transition: $duration all;
      
      &:hover { 
        margin: 0 40px;
        transform: scale(1.2);
      }
      
    }
    
    a {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;
      
      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      
    }
    
  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
    </style>

{% endblock head %}

{% block content %}
    <main class="bg-primary_black min-h-screen w-full">
        <section class="border-red-700 border-b-2 border-opacity-75 h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover bg-black bg-blend-overlay bg-opacity-25" style="background-image: url('{{filmes_alta.first.thumb.url}}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{filmes_alta.first.titulo}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{filmes_alta.first.descricao|slice:":110"}}...
                </p>
                <div class="flex my-4">
                    <a href="{% url 'filme:detalhesfilme' filmes_alta.first.id %}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Preview
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>

        <section class="bg-primary_black flex justify-center py-10">
            <div class="p-8 w-10/12 relative">
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <div class="wrapper">
                    <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl page"> ‹ </a>
                        {% for filme in filmes_recentes %}
                            {% if forloop.counter < 5 %}
                            <div class="item h-64 w-1/4 m-4">
                                <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                                </a>
                            </div>
                            {% endif %}
                        {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl"> › </a>
                    </section>
                    {% if filmes_recentes|length > 4 %}
                        <section id="section2" class="flex flex-nowrap items-center justify-center">
                            <a href="#section1" class="arrow__btn text-6xl">‹</a>
                            {% for filme in filmes_recentes %}
                                {% if forloop.counter > 4 %}
                                    <div class="item h-64 w-1/4 m-4">
                                        <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                            <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                                        </a>
                                    </div>
                                {% endif %}
                            {% endfor %}
                                <a href="#section1" class="arrow__btn text-6xl">›</a>
                        </section>
                    {% endif %}
                  </div>
            </div>
        </section>

        <section class="bg-primary_black flex justify-center py-10">
            <div class="p-8 w-10/12 relative">
                <h2 class="text-gray-200 text-2xl font-medium">
                    Em Alta
                </h2>
                <div class="wrapper">
                    <section id="section3" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section4" class="arrow__btn text-6xl page"> ‹ </a>
                        {% for filme in filmes_alta %}
                            {% if forloop.counter < 5 %}
                            <div class="item h-64 w-1/4 m-4">
                                <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                                </a>
                            </div>
                            {% endif %}
                        {% endfor %}
                    <a href="#section4" class="arrow__btn text-6xl"> › </a>
                    </section>
                    {% if filmes_recentes|length > 4 %}
                        <section id="section4" class="flex flex-nowrap items-center justify-center">
                            <a href="#section3" class="arrow__btn text-6xl">‹</a>
                            {% for filme in filmes_alta %}
                                {% if forloop.counter > 4 %}
                                    <div class="item h-64 w-1/4 m-4">
                                        <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                            <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                                        </a>
                                    </div>
                                {% endif %}
                            {% endfor %}
                                <a href="#section3" class="arrow__btn text-6xl">›</a>
                        </section>
                    {% endif %}
                  </div>
            </div>
        </section>
    </main>
{% endblock %}

filme/templates/filme/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
    Primeflix - Home
{% endblock %}

{% block content%}
<header class="min-h-screen bg-black bg-blend-overlay bg-opacity-75 showcase border-red-600 border-b-8 flex justify-center items-center bg-no-repeat" style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Filmes e séries da Primeflix, tudo em um só lugar.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Assista onde quiser. Cancele quando quiser.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Quer começar? Coloque seu e-mail abaixo para acessar.
        </h4>
        
        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <form method="post" class="w-6/12 justify-center">
                    <div class="flex flex-grow items-stretch">
                        <input class="text-black py-2 px-3">
                    <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                        <span>
                            Acessar
                        </span>
                        <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                    </button>
                    </div>
                </form>
                </a>
            </div>
        </div>
    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-red-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Enjoy on your TV.
        </h2>
        <h5 class="md:text-xl text-lg">
            Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-red-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex justify-center items center">
        <img src="{% static 'images/mobile-0819.jpg' %}">
    </div>
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Download your shows to watch offline.
        </h2>
        <h5 class="md:text-xl text-lg">
            Save your favorites easily and always have something to watch.
        </h5>
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-red-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Create profiles for kids.
        </h2>
        <h5 class="md:text-xl text-lg">
            Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
    </div>
</section>

{% endblock %}

filme/templates/filme/teste.html
<head>
    <meta charset="UTF-8">
    <title>
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    <body class="text-center">
        <h1 class="text-red-600 text-5xl font-bold">
           Tutorial and Example
        </h1>
        <b>Space Between Class - Tailwind CSS </b>
        <div class="py-4 mx-4 space-y-4">
            <div class="bg-red-400 h-16 rounded-lg
                        border-2 border-green-800">1</div>
            <div class="py-4 bg-red-400 h-16 rounded-lg
                        border-2 border-green-800">2</div>
            <div class="bg-red-400 h-16 rounded-lg
                        border-2 border-green-800">3</div>
            <div class="bg-red-400 h-16 rounded-lg
                        border-2 border-green-800">4</div>
        </div>
</body>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
</head>
<body class="bg-black text-gray-100" >
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %} 
    <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
</body>
</html>

templates/navbar.html
{% load static %}
<nav class="bg-black bg-blend-overlay bg-opacity-75 w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img class="w-3/12" src="{% static 'images/logo.png' %}"></img>
        </a>
    </div>
    <div class="w-6/12 flex flex-nowrap justify-end">
        <div class="mr-2">
            <form>
                <input type="text" class="py-1 px-2 rounded-md text-black" placeholder="Pesquisar..."> </input>
            </form>
        </div>
        <div class="mr-2">
            <a href="#">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Login
                </button>
            </a>
            </div>
        <div class="mr-2">
            <a href="#">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Editar Perfil
                </button>
            </a>
        </div>
    </div>
</nav>